# Neden NumPy?

In [7]:
a = [1,2,3,4]
b = [2,3,4,5]

In [9]:
ab = []
for i in range (0, len(a)):
    ab.append(a[i]*b[i])
    
ab

[2, 6, 12, 20]

In [10]:
import numpy as np

In [11]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [12]:
a*b

array([ 2,  6, 12, 20])

optimizasyon anlamında iyileştirme sunar, 
analitik anlamda vektörel ve nümerik hesaplama imkanı sağlar.

# NumPy Array'i Oluşturmak

In [17]:
import numpy as np

In [18]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [19]:
a = np.array([1,2,3,4,5])

In [20]:
type(a)

numpy.ndarray

In [23]:
np.array([3.14, 4, 2, 13], dtype = "int")

array([ 3,  4,  2, 13])

In [24]:
#sifirdan array olsuturma

In [26]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [29]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [30]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [34]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [36]:
np.random.normal(10,4,(3,4))

array([[16.25018178,  6.50367803, 11.87788738, 10.90287499],
       [ 4.86405688, 10.90855438,  5.94190302, 12.97388085],
       [ 4.31073311, 13.76608151,  4.46520725,  7.50323679]])

In [37]:
np.random.randint(0,10, (3,3))

array([[3, 3, 6],
       [0, 6, 8],
       [5, 4, 4]])

# Özellikleri

* **ndim**: boyut sayısı
* **shape**: boyut bilgisi
* **size**: toplam eleman sayısı
* **dtype**: array veri tipi

In [39]:
import numpy as pd

In [40]:
np.random.randint(10, size = 10)

array([6, 5, 4, 4, 8, 3, 7, 0, 4, 8])

In [41]:
a = np.random.randint(10, size = 10)

In [43]:
a.ndim

1

In [44]:
a.shape

(10,)

In [45]:
a.size

10

In [46]:
a.dtype

dtype('int32')

In [47]:
b = np.random.randint(10, size = (3,5))

In [48]:
b

array([[4, 1, 2, 7, 0],
       [5, 3, 6, 4, 5],
       [4, 3, 9, 8, 3]])

In [49]:
b.ndim

2

In [50]:
b.shape

(3, 5)

In [51]:
b.size

15

In [52]:
b.dtype

dtype('int32')

# Yeniden Şekillendirme

In [53]:
import numpy as np

In [54]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
a = np.arange(1,10)

In [57]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
a.ndim

1

In [62]:
b = a.reshape((1,9))

In [63]:
b.ndim

2

In [64]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

# Array Birleştirme (Concatenation)

In [65]:
import numpy as np

In [66]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [67]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [68]:
z = np.array([7,8,9])

In [69]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
#iki boyut

In [74]:
a = np.array([[1,2,3], [4,5,6]])

In [75]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [79]:
np.concatenate([a,a], axis =1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Array Ayırma (Splitting)

In [80]:
import numpy as np

In [83]:
x = np.array([1,2,3,88,88,3,2,1])

In [85]:
np.split(x, (3,5))

[array([1, 2, 3]), array([88, 88]), array([3, 2, 1])]

In [86]:
a,b,c = np.split(x, (3,5))

In [87]:
a

array([1, 2, 3])

In [88]:
b

array([88, 88])

In [89]:
c

array([3, 2, 1])

In [90]:
#iki boyutlu

In [92]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [93]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [94]:
ust, alt = np.vsplit(m, [2])

In [95]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [96]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [97]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [98]:
sol, sag = np.hsplit(m, [2])

In [99]:
sol

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [100]:
sag

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# Array Sıralama (Sorting)

In [101]:
import numpy as np

In [108]:
v = np.array([2,1,3,5,6,4])
v

array([2, 1, 3, 5, 6, 4])

In [109]:
np.sort(v)

array([1, 2, 3, 4, 5, 6])

In [112]:
v.sort()
v

array([1, 2, 3, 4, 5, 6])

In [113]:
#iki boyutlu siralama

In [123]:
m = np.random.normal(20,5, (3, 3))

In [124]:
m

array([[20.6869834 , 12.23165818, 15.24629219],
       [19.17359638, 25.72492321, 21.49919388],
       [25.7986024 , 17.77870108, 18.22487281]])

In [125]:
np.sort(m, axis = 1)

array([[12.23165818, 15.24629219, 20.6869834 ],
       [19.17359638, 21.49919388, 25.72492321],
       [17.77870108, 18.22487281, 25.7986024 ]])

In [126]:
np.sort(m, axis = 0)

array([[19.17359638, 12.23165818, 15.24629219],
       [20.6869834 , 17.77870108, 18.22487281],
       [25.7986024 , 25.72492321, 21.49919388]])

# Index ie Elemanlara Erişmek

In [138]:
import numpy as np
a = np.random.randint(10, size = 10)
a

array([8, 5, 8, 7, 8, 6, 5, 5, 6, 9])

In [139]:
a[0]

8

In [140]:
a[-1]

9

In [141]:
a[0] = 234

In [142]:
a

array([234,   5,   8,   7,   8,   6,   5,   5,   6,   9])

In [143]:
m = np.random.randint(10, size = (3,5))
m

array([[2, 7, 9, 3, 6],
       [1, 3, 4, 3, 5],
       [5, 2, 3, 9, 9]])

In [144]:
m[0,0]

2

In [147]:
m[1,4]

5

In [148]:
m[1,4] = 8325
m

array([[   2,    7,    9,    3,    6],
       [   1,    3,    4,    3, 8325],
       [   5,    2,    3,    9,    9]])

In [149]:
m[0,0] = 3.4
m

array([[   3,    7,    9,    3,    6],
       [   1,    3,    4,    3, 8325],
       [   5,    2,    3,    9,    9]])

# Slicing ile Elemanlara Erişmek - Array Alt Kümesine Erişmek

In [150]:
import numpy as np

In [158]:
a = np.arange(23,43)
a

array([23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
       40, 41, 42])

In [159]:
a[0:3]

array([23, 24, 25])

In [160]:
a[:3]

array([23, 24, 25])

In [161]:
a[3:]

array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42])

In [162]:
a[1::2]

array([24, 26, 28, 30, 32, 34, 36, 38, 40, 42])

In [163]:
a[0::2]

array([23, 25, 27, 29, 31, 33, 35, 37, 39, 41])

In [164]:
#iki boyutlu slice islemleri

In [167]:
m = np.random.randint(10, size = (4,4))
m

array([[2, 4, 9, 7],
       [1, 6, 6, 7],
       [7, 7, 7, 2],
       [6, 8, 2, 0]])

In [168]:
m[:,0]

array([2, 1, 7, 6])

In [169]:
m[0,:]

array([2, 4, 9, 7])

In [170]:
m[1,:]

array([1, 6, 6, 7])

In [172]:
m[0:2, 0:3]

array([[2, 4, 9],
       [1, 6, 6]])

In [176]:
m[1:3, 1:4]

array([[6, 6, 7],
       [7, 7, 2]])

In [177]:
m[::, :2]

array([[2, 4],
       [1, 6],
       [7, 7],
       [6, 8]])

In [180]:
m[:, :2]

array([[2, 4],
       [1, 6],
       [7, 7],
       [6, 8]])

# Alt Küme Üzerinde İşlem Yapmak

In [182]:
import numpy as np
a = np.random.randint(30, size = (5,5))
a

array([[ 5, 29,  4, 22,  4],
       [18, 19,  3, 26, 19],
       [25,  2, 22, 24, 15],
       [26,  3, 17,  3, 12],
       [28,  2, 10, 24, 27]])

In [184]:
alt_a = a[0:3, 0:2]
alt_a

array([[ 5, 29],
       [18, 19],
       [25,  2]])

In [187]:
alt_a [0,0] = 1982
alt_a [1,1] = 1234

In [188]:
alt_a

array([[1982,   29],
       [  18, 1234],
       [  25,    2]])

In [189]:
a

array([[1982,   29,    4,   22,    4],
       [  18, 1234,    3,   26,   19],
       [  25,    2,   22,   24,   15],
       [  26,    3,   17,    3,   12],
       [  28,    2,   10,   24,   27]])

In [190]:
m = np.random.randint(30, size = (5,5))
m

array([[17, 26,  3, 16, 21],
       [20, 28,  7, 16,  2],
       [29, 25, 11,  6, 29],
       [13, 25,  6, 19, 17],
       [24,  3,  7,  5,  5]])

In [191]:
alt_b = m[0:3, 0:2].copy()
alt_b

array([[17, 26],
       [20, 28],
       [29, 25]])

In [192]:
alt_b [0,0] = 54376
alt_b

array([[54376,    26],
       [   20,    28],
       [   29,    25]])

In [193]:
m

array([[17, 26,  3, 16, 21],
       [20, 28,  7, 16,  2],
       [29, 25, 11,  6, 29],
       [13, 25,  6, 19, 17],
       [24,  3,  7,  5,  5]])

# Fancy Index ile Elemanlara Erişmek

In [196]:
import numpy as np
v = np.arange(0, 30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [197]:
v[1]

3

In [199]:
[v[1], v[2], v[3]]

[3, 6, 9]

In [203]:
secilenler = [1,2,3]
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [205]:
v[secilenler]

array([3, 6, 9])

In [206]:
#iki boyuta fancy

In [207]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [272]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [275]:
m[satir, sutun]

array([1, 5])

In [277]:
#basit index ile fancy index

In [278]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [279]:
m[0, [1,2]]

array([1, 2])

In [280]:
#slice ile fancy

In [281]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

# Koşullu Eleman İşlemleri

In [282]:
import numpy as np
v = np.array([1,2,3,4,5])

In [284]:
v > 3

array([False, False, False,  True,  True])

In [285]:
v[v > 3]

array([4, 5])

In [286]:
v[v >= 3]

array([3, 4, 5])

In [287]:
v[v <= 3]

array([1, 2, 3])

In [288]:
v[v == 3]

array([3])

In [289]:
v[v != 3]

array([1, 2, 4, 5])

In [290]:
v * 2

array([ 2,  4,  6,  8, 10])

In [297]:
v /2

array([0.5, 1. , 1.5, 2. , 2.5])

In [300]:
v*4/3

array([1.33333333, 2.66666667, 4.        , 5.33333333, 6.66666667])

In [299]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

# Matematiksel İşlemler

In [301]:
import numpy as np
v = np.array([1,2,3,4,5,])
v

array([1, 2, 3, 4, 5])

In [302]:
v-1

array([0, 1, 2, 3, 4])

In [313]:
v*66

array([ 66, 132, 198, 264, 330])

In [304]:
#ufunc

In [306]:
np.subtract(v,2)

array([-1,  0,  1,  2,  3])

In [308]:
np.add(v,60)

array([61, 62, 63, 64, 65])

In [315]:
np.multiply(v,66)

array([ 66, 132, 198, 264, 330])

In [316]:
np.divide(v,2)

array([0.5, 1. , 1.5, 2. , 2.5])

In [317]:
np.power(v,4)

array([  1,  16,  81, 256, 625], dtype=int32)

In [318]:
v

array([1, 2, 3, 4, 5])

In [319]:
v % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [320]:
np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [321]:
np.absolute([np.array([3])]) #mutlak deger alma

array([[3]])

In [325]:
np.sin(270)

-0.1760459464712114

In [326]:
np.cos(270)

0.9843819506325049

In [328]:
v = np.array([1,2,3,4])

In [329]:
np.log(v)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [331]:
np.log2(v)

array([0.       , 1.       , 1.5849625, 2.       ])

In [332]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125, 0.60205999])

In [333]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\Users\\AUGUSTUS\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\augustus\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 

# İstatistiksel Hesaplamalar

In [336]:
v

array([1, 2, 3, 4])

In [338]:
np.mean(v)

2.5

In [339]:
np.sum(v)

10

In [341]:
v.sum()

10

# NumPy ile İki Bilinmeyenli Denklem Çözümü

In [343]:
import numpy as np

5 * x0 + x1 = 12 <br>
x0 + 3 * x1 = 10

In [344]:
a = np.array([[5,1], [1,3]])
b = np.array([12,10])

In [345]:
a

array([[5, 1],
       [1, 3]])

In [346]:
b

array([12, 10])

In [347]:
x = np.linalg.solve(a, b)
x

array([1.85714286, 2.71428571])

In [349]:
    import numpy as np
    np.array([3.14, 4,6,1.2])

array([3.14, 4.  , 6.  , 1.2 ])

In [351]:
    import numpy as np
    x = np.array([1, 2, 3])
    y = np.array([4, 5, 6])
    np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])